spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    shutdown:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
    instances:
      getAllAccounts:
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          units:
            - 30000
        permitted-number-of-calls-in-half-open-state: 2

  retry:
    instances:
      getAccountByIdRetry:
        max-attempts: 3
        wait-duration:
          units:
            - 2000

  ratelimiter:
    instances:
      getCardByIdLimiter:
        timeout-duration:
          units:
            - 5000
        limit-refresh-period:
          units:
            - 5000
        limit-for-period: 1

